/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as BrokerageRouteImport } from './routes/brokerage'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CryptoRouteImport } from './routes/crypto'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FuturesRouteImport } from './routes/futures'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as WhalesRouteImport } from './routes/whales'
import { Route as AssetIdRouteImport } from './routes/asset.$id'
import { Route as SymbolMarketSymbolRouteImport } from './routes/symbol.$market.$symbol'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerageRoute = BrokerageRouteImport.update({
  id: '/brokerage',
  path: '/brokerage',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CryptoRoute = CryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturesRoute = FuturesRouteImport.update({
  id: '/futures',
  path: '/futures',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const WhalesRoute = WhalesRouteImport.update({
  id: '/whales',
  path: '/whales',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdRoute = AssetIdRouteImport.update({
  id: '/asset/$id',
  path: '/asset/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SymbolMarketSymbolRoute = SymbolMarketSymbolRouteImport.update({
  id: '/symbol/$market/$symbol',
  path: '/symbol/$market/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/brokerage': typeof BrokerageRoute
  '/community': typeof CommunityRoute
  '/crypto': typeof CryptoRoute
  '/discover': typeof DiscoverRoute
  '/futures': typeof FuturesRoute
  '/lists': typeof ListsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/terminal': typeof TerminalRoute
  '/wallets': typeof WalletsRoute
  '/whales': typeof WhalesRoute
  '/asset/$id': typeof AssetIdRoute
  '/symbol/$market/$symbol': typeof SymbolMarketSymbolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/brokerage': typeof BrokerageRoute
  '/community': typeof CommunityRoute
  '/crypto': typeof CryptoRoute
  '/discover': typeof DiscoverRoute
  '/futures': typeof FuturesRoute
  '/lists': typeof ListsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/terminal': typeof TerminalRoute
  '/wallets': typeof WalletsRoute
  '/whales': typeof WhalesRoute
  '/asset/$id': typeof AssetIdRoute
  '/symbol/$market/$symbol': typeof SymbolMarketSymbolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/brokerage': typeof BrokerageRoute
  '/community': typeof CommunityRoute
  '/crypto': typeof CryptoRoute
  '/discover': typeof DiscoverRoute
  '/futures': typeof FuturesRoute
  '/lists': typeof ListsRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/terminal': typeof TerminalRoute
  '/wallets': typeof WalletsRoute
  '/whales': typeof WhalesRoute
  '/asset/$id': typeof AssetIdRoute
  '/symbol/$market/$symbol': typeof SymbolMarketSymbolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/auth'
    | '/backtest'
    | '/brokerage'
    | '/community'
    | '/crypto'
    | '/discover'
    | '/futures'
    | '/lists'
    | '/portfolio'
    | '/pricing'
    | '/scanner'
    | '/settings'
    | '/stocks'
    | '/terminal'
    | '/wallets'
    | '/whales'
    | '/asset/$id'
    | '/symbol/$market/$symbol'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/auth'
    | '/backtest'
    | '/brokerage'
    | '/community'
    | '/crypto'
    | '/discover'
    | '/futures'
    | '/lists'
    | '/portfolio'
    | '/pricing'
    | '/scanner'
    | '/settings'
    | '/stocks'
    | '/terminal'
    | '/wallets'
    | '/whales'
    | '/asset/$id'
    | '/symbol/$market/$symbol'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/auth'
    | '/backtest'
    | '/brokerage'
    | '/community'
    | '/crypto'
    | '/discover'
    | '/futures'
    | '/lists'
    | '/portfolio'
    | '/pricing'
    | '/scanner'
    | '/settings'
    | '/stocks'
    | '/terminal'
    | '/wallets'
    | '/whales'
    | '/asset/$id'
    | '/symbol/$market/$symbol'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BacktestRoute: typeof BacktestRoute
  BrokerageRoute: typeof BrokerageRoute
  CommunityRoute: typeof CommunityRoute
  CryptoRoute: typeof CryptoRoute
  DiscoverRoute: typeof DiscoverRoute
  FuturesRoute: typeof FuturesRoute
  ListsRoute: typeof ListsRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  StocksRoute: typeof StocksRoute
  TerminalRoute: typeof TerminalRoute
  WalletsRoute: typeof WalletsRoute
  WhalesRoute: typeof WhalesRoute
  AssetIdRoute: typeof AssetIdRoute
  SymbolMarketSymbolRoute: typeof SymbolMarketSymbolRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokerage': {
      id: '/brokerage'
      path: '/brokerage'
      fullPath: '/brokerage'
      preLoaderRoute: typeof BrokerageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crypto': {
      id: '/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof CryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futures': {
      id: '/futures'
      path: '/futures'
      fullPath: '/futures'
      preLoaderRoute: typeof FuturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whales': {
      id: '/whales'
      path: '/whales'
      fullPath: '/whales'
      preLoaderRoute: typeof WhalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$id': {
      id: '/asset/$id'
      path: '/asset/$id'
      fullPath: '/asset/$id'
      preLoaderRoute: typeof AssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symbol/$market/$symbol': {
      id: '/symbol/$market/$symbol'
      path: '/symbol/$market/$symbol'
      fullPath: '/symbol/$market/$symbol'
      preLoaderRoute: typeof SymbolMarketSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BacktestRoute: BacktestRoute,
  BrokerageRoute: BrokerageRoute,
  CommunityRoute: CommunityRoute,
  CryptoRoute: CryptoRoute,
  DiscoverRoute: DiscoverRoute,
  FuturesRoute: FuturesRoute,
  ListsRoute: ListsRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  StocksRoute: StocksRoute,
  TerminalRoute: TerminalRoute,
  WalletsRoute: WalletsRoute,
  WhalesRoute: WhalesRoute,
  AssetIdRoute: AssetIdRoute,
  SymbolMarketSymbolRoute: SymbolMarketSymbolRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
